### ISSUE TITLE
Context access might be invalid

### ISSUE THREAD

**Issue by RDavis3000** [github/vscode-github-actions#96]
Problem:
I am using a lot of repository environment variables, access via the vars context. The plugin is raising "Context access might be invalid:" warnings on every line which makes it difficult to spot actual issues and is making me sad.

Proposed solution:

I think that this functionality isn't relevant for vars/secrets contexts because there is no way for them to be discernible by the plugin.

It would be great to be able to configure the plugin to ignore these warnings in some circumstances (such as by a string pattern or by check boxes for various contexts. Or at least to be able to turn it off globally.

**Additional context**
Related to 
[https://github.com/github/vscode-github-actions/issues/67][https://github.com/github/vscode-github-actions/issues/47]

Screenshot of my minimap to show you what I'm dealing with, all the yellow lines are this warning!

![Screenshot 2023-04-07 110338](https://user-images.githubusercontent.com/16304586/230579635-eacf24de-a04c-4f0b-9b0c-cedfc0191c9e.png)

**Comment by elbrenn** [comment]
> I think that this functionality isn't relevant for vars/secrets contexts because there is no way for them to be discernible by the plugin.

The extension hits GitHub secret/ variable APIs to determine which secrets and variables are available to the workflow. Have you signed in to GitHub in the extension? If so can you try reloading VS Code

**Comment by doubleforte** [comment]
I'm signed in, but we have a few env vars that are set by previous steps -- not in the `env:` setting or in GitHub's environment, so the plugin doesn't know about them and complains.

Would be nice to be able to either turn off this error globally, or suppress it on a line-by-line or full-file case. Similar to Typescript's `// @ts-ignore` or similar.

**Comment by max-sixty** [comment]
I'm getting these throughout my project — five of them in this file, for example: https://github.com/prql/prql/blob/d09c3acad05b35b3f2565c51e045b689acea10b4/.github/workflows/release.yaml#L103

The secrets do exist — here's a screenshot from https://github.com/PRQL/prql/settings/secrets/actions

<img width="442" alt="image" src="https://github.com/github/vscode-github-actions/assets/5635139/90717c96-250c-465e-8c55-0679ad42a2cb">

I'm signed in on the GitHub Pull Requests extension. Should I be signed in on this extension too? How? (Searching for "Sign in" in the command palette doesn't find any additional hits).

Thanks!

**Comment by elbrenn** [comment]
@max-sixty if you select the Actions Extension tab, do you see a prompt to sign in? ![Screenshot Actions Extension tab highlighted](https://github.com/github/vscode-github-actions/assets/34719884/d23ed048-e6ba-46b8-a9fd-24e82aee8616)

**Comment by elbrenn** [comment]
@doubleforte 

> I'm signed in, but we have a few env vars that are set by previous steps -- not in the env: setting or in GitHub's environment, so the plugin doesn't know about them and complains.

This sounds similar to the issue tracked in https://github.com/github/vscode-github-actions/issues/41 but for variables instead of secrets. 

> Would be nice to be able to either turn off this error globally, or suppress it on a line-by-line or full-file case. Similar to Typescript's // @ts-ignore or similar.

Tracked in https://github.com/github/vscode-github-actions/issues/123

**Comment by elbrenn** [comment]
It sounds like the request here is "disable `vars` context validation when not logged in. Updating the title to reflect this more specifically. Let us know if that does not cover your scenario. 

The extension already does this for other contexts, such as `secrets`.

**Comment by max-sixty** [comment]
> @max-sixty if you select the Actions Extension tab, do you see a prompt to sign in?

My issue was a case of https://github.com/github/vscode-github-actions/issues/121. All fixed now!

**Comment by RDavis3000** [comment]
> It sounds like the request here is "disable `vars` context validation when not logged in. Updating the title to reflect this more specifically. Let us know if that does not cover your scenario.
> 
> The extension already does this for other contexts, such as `secrets`.

No, I AM logged in and the extension can see the variables fine! And yet the wall of yellow persists. 

So it's not related to being logged in. 

Secrets are working fine, so its just variables which are borked.

![image](https://github.com/github/vscode-github-actions/assets/16304586/dadfd7ac-da6a-4a06-ae96-de794a068248)

**Comment by RDavis3000** [comment]
> > I think that this functionality isn't relevant for vars/secrets contexts because there is no way for them to be discernible by the plugin.
> 
> The extension hits GitHub secret/ variable APIs to determine which secrets and variables are available to the workflow. Have you signed in to GitHub in the extension? If so can you try reloading VS Code

sorry for the delay, github notifications go to spam because of the firehose of 'github action failed' messages I get (JIRA and Azure DevOps are treated similarly, WFH and all emails to spam is the only way to be productive I've found).

As mentioned above, I am logged in and have restarted VS, issue persists.

![image](https://github.com/github/vscode-github-actions/assets/16304586/2dd1ea6a-5b9e-4f66-93b7-15fa57439b35)

**Comment by elbrenn** [comment]
@RDavis3000 are those repository, environment, or org variables

**Comment by RDavis3000** [comment]
> @RDavis3000 are those repository, environment, or org variables?
> 
> If they are environment variables, can you include the portion of your workflow file where you set the environment for the job in your screenshot
@elbrenn they're repository variables, set by GitHub Cli:

gh variable set -e DEV -f someFile.env

This is how the reference is setup:

![image](https://github.com/github/vscode-github-actions/assets/16304586/3f794c81-735b-4b3a-9b69-67dc00e47c66)

**Comment by vincent-hoodoo** [comment]
I was getting warnings when I wasn't logged in, so I logged in, restarted VSCode and it worked fine, the warnings are gone and I can see the completion for all secrets when I type `secrets.`.

However, the warnings are still showing in the "Problems" tabs. When I click on a problem in the "Problems" tab, even though I already have that file open just above (displaying the path relative to the workspace), it opens a new tab, with the full path as file name, and this file lists the warnings..

**Comment by RDavis3000** [comment]
> Thabks for all of this context!
> 
> The `-e` in that command indicates that it an environment variable associated with the environment `DEV`.
> 
> On line 17 of your workflow, you are setting your environment (presumably to `DEV` or some other environment) via an expression.
> 
> We should suppress validation for variables if there is an environment set via an expression. We have #41 tracking doing this for secrets

That makes sense, hopefully it gets tweaked soon :)

**Comment by felipesu19** [comment]
I've updated the title, I'm also quoting the relevant post here so whoever picks this up knows where to start the work: 

 ```
Thabks for all of this context!

The `-e` in that command indicates that it an environment variable associated with the environment `DEV`.

On line 17 of your workflow, you are setting your environment (presumably to `DEV` or some other environment) via an expression.

We should suppress validation for variables if there is an environment set via an expression. We have https://github.com/github/vscode-github-actions/issues/41 tracking doing this for secrets
```

**Comment by johnrom** [comment]
In addition to suppressing these warnings when an environment can't be determined, I'd like to suggest the option of a hint here. I prefer a comment-based approach so it doesn't affect the way builds work. However, if it's easier to evaluate expressions or parse inputs during static analysis, that might work depending on the situation.

- Providing a static analysis value hint comment in one of these places:
  ```yml
  # see https://carvel.dev/ytt/docs/v0.44.0/yaml-primer/#annotating-yaml for an example of a parser which uses annotations
  # I based this format off of that one, but any comment-based hinting would work
  jobs: 
    deploy:
      runs-on: ubuntu-latest
      #@github/static value=staging
      environment: ${{ inputs.deployment-environment }} #@github/static value=staging
  ```
- Evaluating the default of an input:
  ```yml
  on:
    workflow_call:
      inputs:
        deployment-environment:
          required: true
          default: staging # use staging for static checking by evaluating each input with default or null
          type: string
  ```
- Providing a fallback value to the environment that can be used for static checking:
  ```yml
  jobs: 
    deploy:
      runs-on: ubuntu-latest
      environment: ${{ inputs.deployment-environment || 'staging' }}
  ```

It would be great to be able to hint to bring back validation for secrets, because as of now it's very easy to make mistakes within nested actions.

**Comment by alles60** [comment]
The problem is still present in v0.26.2. The environment of our jobs is set via a `choice` input:
```yaml
 workflow_dispatch:
    inputs:
      destination:
        description: 'Promotion destination'
        type: choice
        required: true
        default: ap
        options:
          - ap
          - pr
[...]
 environment: ${{ github.event.inputs.destination }}
```

So, for every variable in an environment, I get the warning. But every variable defined at the repository level doesn't have the warning.
